Purge definition of G_GNUC_FALLTHROUGH
GLib>=2.69 annonated macros with version tags. Since Libvirt currently
sets GLIB_VERSION_MAX_ALLOWED 2.48, this causes errors like following
during build:

../src/util/virconf.c:966:13: error: Not available before 2.60 [-Werror]
  966 |         G_GNUC_FALLTHROUGH;
      |             ^~~~~~~~~~~~~~~

Undefine G_GNUC_FALLTHROUGH macros and redfine to fix this issue. Drop
this once Libvirt migrates to 2.69 or never glib.

https://lists.fedorahosted.org/archives/list/scm-commits@lists.fedoraproject.org/thread/GBUN6T4TLZBIZY55IEJCAKIA2AGRIP63/
is the reference link for this commit.

Signed-off-by: Praveen K Paladugu <prapal@linux.microsoft.com>